# Generated by Django 4.2.7 on 2024-01-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=500)),
                ('customer_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('return_reason', models.TextField(null=True)),
                ('return_tracking', models.CharField(max_length=50)),
                ('original_order_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'open'), (2, 'close')], default=1)),
                ('return_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_id', to='management.return')),
            ],
        ),
    ]
